#!/bin/sh

# List:
current_workspace=$(xdotool get_desktop)
minimized_programs=$(min-client --socket /tmp/min.so --workspace_id $current_workspace --action list)

# Select:
chosen_title_time=$(echo "$minimized_programs" | cut -f1,3 | rofi -dmenu -i)
chosen_time=$(echo $chosen_title_time | rev | cut -d' ' -f-2 | rev)
chosen_title=$(echo $chosen_title_time | rev | cut -d' ' -f3- | rev)
chosen_id=$(echo "$minimized_programs" | grep "$chosen_time" | cut -f2)

# Recover:
xdotool windowmap "$chosen_id"
min-client --socket /tmp/min.so --workspace_id $current_workspace --window_id $chosen_id --action recover

