#!/bin/sh

# List:
current_workspace=$(xdotool get_desktop)
minimized_programs=$(min-client --socket /tmp/min.so --workspace_id $current_workspace --action list | nl -w1)

# Select:
selection=$(echo "$minimized_programs" | cut -f1,2,4 | rofi -dmenu -i)
chosen_line=$(echo $selection | cut -f1)
chosen_id=$(echo "$minimized_programs" | awk -F' ' -v line_no=$chosen_line 'line_no~$1{print $(NF-2)}')

# Recover:
xdotool windowmap "$chosen_id"
min-client --socket /tmp/min.so --workspace_id $current_workspace --window_id $chosen_id --action recover

